baseurl = "https://blog.gruezo.com/"
languageCode = "en-us"
pagination.pagerSize = 5
theme = "re-terminal"

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  favicon = "/favicon.ico"
  readingTime = true
  # [params.banner]
  #   dismissible = false
  #   text = "HOME"
  #   url = "https://gruezo.com"

[languages]
  [languages.en.params]
    title = "GRUEZO | AI, Machine Learning, Data Systems"
    subtitle = "Sharing my journey in AI, ML, and Data Engineering. I will be exploring hands-on projects, deep learning, MLOps, and doing deep dives into AI-driven technologies and data systems."
    keywords = "AI, Machine Learning, Data Engineering, AI Engineer, MLOps, Deep Learning, Artificial Intelligence, AI Software Development, Data Pipelines, ETL, Cloud AI, Bioinformatics AI, Predictive Analytics, AI-powered Applications, Neural Networks"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Gruezo"
      logoHomeLink = "https://gruezo.com/"

[languages.en.menu]
  # [[languages.en.menu.main]]
  #   identifier = "submenu"
  #   name = "Sub menus"
  #   weight = 10
  [[languages.en.menu.main]]
    identifier = "main"
    name = "Main"
    url = "/"
    weight = 1
  # [[languages.en.menu.main]]
  #   identifier = "subabout"
  #   name = "About"
  #   url = "/about"
  #   parent = "submenu"
  # [[languages.en.menu.main]]
  #   identifier = "subshowcase"
  #   name = "Showcase"
  #   url = "/showcase"
  #   parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2
  [[languages.en.menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources"
    weight = 3


# Only for demo deploy perpous
[module]
  # [[module.mounts]]
  #   source = 'demoSite/content'
  #   target = 'content'
  # [[module.mounts]]
  #   source = 'demoSite/static'
  #   target = 'static'
  # [[module.mounts]]
  #   source = 'static'
  #   target = 'static'
  # [[module.mounts]]
  #   source = 'layouts'
  #   target = 'layouts'
  # [[module.mounts]]
  #   source = 'demoSite/layouts'
  #   target = 'layouts'
  # [[module.mounts]]
  #   source = 'archetypes'
  #   target = 'archetypes'
  #replacements = "github.com/mirus-ua/hugo-theme-re-terminal -> themes/re-terminal"

# [[module.imports]]
  # path = 'github.com/mirus-ua/hugo-theme-re-terminal'

# Allow raw html

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
